JSON-RPC 2.0 Modern C++ Library
jsonrpc::FramedTransport Class Reference
Base class for framed transport mechanisms.
#include <framed_transport.hpp>
Protected Member Functions
void FrameMessage (std::ostream &output, const std::string &message)
Constructs a framed message.
std::string DeframeMessage (std::istream &input)
Receives a framed message.
Detailed Description
Base class for framed transport mechanisms.
Provides basic functionality for sending and receiving framed messages.
Definition at line 12 of file framed_transport.hpp.
Member Function Documentation
DeframeMessage()
std::string jsonrpc::FramedTransport::DeframeMessage (std::istream & input) protected
Receives a framed message.
Reads headers to determine the content length, then reads the message content based on that length.
Parameters
input The input stream to read the framed message.
Returns
The received message.
Definition at line 32 of file framed_transport.cpp.
{
  spdlog::info("FramedTransport deframing message");
  std::string line;
  std::string headers;
  int content_length = 0;
  bool content_length_found = false;
  // Read headers
  while (std::getline(input, line) && !line.empty() && line != "\r") {
    headers += line + "\n";
    std::istringstream line_stream(line);
    std::string header_key;
    if (std::getline(line_stream, header_key, ':')) {
      std::string header_value;
      if (std::getline(line_stream >> std::ws, header_value)) {
        spdlog::debug("Parsed header: {}: {}", header_key, header_value);
        if (header_key == "Content-Length") {
          content_length = parseContentLength(header_value);
          content_length_found = true;
        }
      }
    }
  }
  if (!content_length_found) {
    spdlog::error("Content-Length header missing");
    throw std::runtime_error("Content-Length header missing");
  }
  // Read content
  spdlog::debug(
      "FramedTransport reading content of length: {}", content_length);
  std::string content(content_length, '\0');
  input.read(&content[0], content_length);
  if (input.gcount() != content_length) {
    throw std::runtime_error("Failed to read the expected content length");
  }
  return content;
}
Referenced by jsonrpc::FramedStdioServerTransport::Listen(), and jsonrpc::FramedStdioClientTransport::ReadResponse().
FrameMessage()
void jsonrpc::FramedTransport::FrameMessage (std::ostream & output, const std::string & message) protected
Constructs a framed message.
Constructs a JSON message as a string with additional headers for Content-Length and Content-Type, similar to HTTP.
Parameters
output The output stream to write the framed message.
message The message to be framed.
Definition at line 10 of file framed_transport.cpp.
{
  spdlog::debug("FramedTransport framing message: {}", message);
  output << "Content-Length: " << message.size() << "\r\n"
         << "Content-Type: application/vscode-jsonrpc; charset=utf-8\r\n"
         << "\r\n"
         << message;
}
Referenced by jsonrpc::FramedStdioServerTransport::Listen(), and jsonrpc::FramedStdioClientTransport::SendRequest().
The documentation for this class was generated from the following files:
include/jsonrpc/transports/framed_transport.hpp
src/transports/framed_transport.cpp