JSON-RPC 2.0 Modern C++ Library
jsonrpc::server::Response Class Reference
Represents a JSON-RPC response.
#include <response.hpp>
Public Member Functions
Response ()=delete
Deleted default constructor to prevent instantiation without data.
Response (const Response &)=delete
Deleted copy constructor to prevent copying of Response objects.
Response & operator= (const Response &)=delete
Deleted copy assignment operator to prevent assignment.
Response (Response &&other) noexcept
Move constructor for efficient resource management.
nlohmann::json ToJson () const
Serializes the Response object to a JSON object.
std::string ToStr () const
Serializes the Response object to a string.
Static Public Member Functions
static Response FromUserResponse (const nlohmann::json &responseJson, std::optional< nlohmann::json > id)
Creates a Response object from a JSON object that represents a user response.
static Response CreateResult (const nlohmann::json &result, const std::optional< nlohmann::json > &id)
Creates a successful Response object.
static Response CreateLibError (LibErrorKind errorKind, const std::optional< nlohmann::json > &id=std::nullopt)
Creates a Response object for a library error.
static Response CreateUserError (const nlohmann::json &error, const std::optional< nlohmann::json > &id)
Creates a Response object for a user error.
Detailed Description
Represents a JSON-RPC response.
Definition at line 25 of file response.hpp.
Constructor & Destructor Documentation
Response() [1/3]
jsonrpc::server::Response::Response () delete
Deleted default constructor to prevent instantiation without data.
Response() [2/3]
jsonrpc::server::Response::Response (const Response &) delete
Deleted copy constructor to prevent copying of Response objects.
Response() [3/3]
jsonrpc::server::Response::Response (Response && other) noexcept
Move constructor for efficient resource management.
Parameters
other The response to move from.
Definition at line 15 of file response.cpp.
    : response_(std::move(other.response_)) {
}
Member Function Documentation
CreateLibError()
Response jsonrpc::server::Response::CreateLibError (LibErrorKind errorKind, const std::optional< nlohmann::json > & id = std::nullopt) static
Creates a Response object for a library error.
Parameters
errorKind The kind of library error.
id The ID of the request. It can be a JSON object or null.
Returns
A Response object indicating a library error.
Definition at line 65 of file response.cpp.
{
  const auto &[code, message] = errorInfoMap.at(errorKind);
  nlohmann::json errorResponse = CreateErrorResponse(message, code, id);
  return Response{std::move(errorResponse)};
}
Referenced by jsonrpc::server::Dispatcher::DispatchRequest().
CreateResult()
Response jsonrpc::server::Response::CreateResult (const nlohmann::json & result, const std::optional< nlohmann::json > & id) static
Creates a successful Response object.
Parameters
result The result of the method call.
id The ID of the request. It can be a JSON object or null.
Returns
A Response object indicating success.
Definition at line 39 of file response.cpp.
{
  nlohmann::json response = {{"jsonrpc", "2.0"}, {"result", result}};
  if (id.has_value()) {
    response["id"] = id.value();
  }
  return Response{std::move(response)};
}
Referenced by FromUserResponse().
CreateUserError()
Response jsonrpc::server::Response::CreateUserError (const nlohmann::json & error, const std::optional< nlohmann::json > & id) static
Creates a Response object for a user error.
Parameters
error The JSON object representing the error.
id The ID of the request. It can be a JSON object or null.
Returns
A Response object indicating a user error.
Definition at line 48 of file response.cpp.
{
  nlohmann::json response = {{"jsonrpc", "2.0"}, {"error", error}};
  if (id.has_value()) {
    response["id"] = id.value();
  }
  return Response{std::move(response)};
}
Referenced by FromUserResponse().
FromUserResponse()
Response jsonrpc::server::Response::FromUserResponse (const nlohmann::json & responseJson, std::optional< nlohmann::json > id) static
Creates a Response object from a JSON object that represents a user response.
Parameters
responseJson The JSON object representing the user response.
id The ID of the request. It can be a JSON object or null.
Returns
A Response object.
Definition at line 27 of file response.cpp.
{
  if (responseJson.contains("result")) {
    return CreateResult(responseJson["result"], id);
  } else if (responseJson.contains("error")) {
    return CreateUserError(responseJson["error"], id);
  } else {
    throw std::invalid_argument(
        "Response JSON must contain either 'result' or 'error' field");
  }
}
References CreateResult(), and CreateUserError().
operator=()
Response & jsonrpc::server::Response::operator= (const Response &) delete
Deleted copy assignment operator to prevent assignment.
ToJson()
nlohmann::json jsonrpc::server::Response::ToJson () const
Serializes the Response object to a JSON object.
Returns
The JSON representation of the response.
Definition at line 57 of file response.cpp.
{
  return response_;
}
ToStr()
std::string jsonrpc::server::Response::ToStr () const
Serializes the Response object to a string.
Returns
The string representation of the response.
Definition at line 61 of file response.cpp.
{
  return response_.dump();
}
Referenced by jsonrpc::server::Dispatcher::DispatchRequest().
The documentation for this class was generated from the following files:
include/jsonrpc/server/response.hpp
src/server/response.cpp