JSON-RPC 2.0: json_rpc::FramedStdioServerTransport Class Reference
json_rpc::FramedStdioServerTransport Class Reference
Server transport using framed stdio for communication.
#include <framed_stdio_server_transport.hpp>
Protected Member Functions
void Listen () override
Listens for incoming messages and dispatches them to the appropriate handlers.
Protected Member Functions inherited from json_rpc::FramedTransport
void SendMessage (const std::string &message)
Sends a framed message.
std::string ReceiveMessage ()
Receives a framed message.
Additional Inherited Members
Public Member Functions inherited from json_rpc::ServerTransport
ServerTransport ()
Constructs a ServerTransport object.
virtual ~ServerTransport ()=default
Virtual destructor for ServerTransport.
virtual void Start ()
Starts the transport.
virtual void Stop ()
Stops the transport.
void SetDispatcher (Dispatcher *dispatcher)
Sets the dispatcher for the transport.
bool IsRunning () const
Checks if the transport is running.
Protected Attributes inherited from json_rpc::ServerTransport
std::atomic< bool > running_
Atomic flag indicating if the transport is running.
Dispatcher * dispatcher_
Pointer to the Dispatcher object.
Detailed Description
Server transport using framed stdio for communication.
This class implements the ServerTransport interface using framed stdio as the underlying transport mechanism.
Definition at line 17 of file framed_stdio_server_transport.hpp.
Member Function Documentation
Listen()
void json_rpc::FramedStdioServerTransport::Listen () override protected virtual
Listens for incoming messages and dispatches them to the appropriate handlers.
Implements json_rpc::ServerTransport.
Definition at line 12 of file framed_stdio_server_transport.cpp.
{
  spdlog::info("FramedStdioServerTransport listening");
  if (!dispatcher_) {
    spdlog::error("Dispatcher is not set.");
    return;
  }
  while (IsRunning()) {
    try {
      std::string content = ReceiveMessage();
      std::optional<std::string> response =
          dispatcher_->DispatchRequest(content);
      if (response.has_value()) {
        spdlog::debug("FramedStdioServerTransport dispatching response: {}",
            response.value());
        SendMessage(response.value());
      }
    } catch (const std::runtime_error &e) {
      spdlog::error(
          "Runtime error in FramedStdioServerTransport: {}", e.what());
      break; // Exit loop on error
    }
  }
}
References json_rpc::ServerTransport::dispatcher_, json_rpc::Dispatcher::DispatchRequest(), json_rpc::ServerTransport::IsRunning(), json_rpc::FramedTransport::ReceiveMessage(), and json_rpc::FramedTransport::SendMessage().
The documentation for this class was generated from the following files:
include/json_rpc/transports/framed_stdio_server_transport.hpp
src/transports/framed_stdio_server_transport.cpp