JSON-RPC 2.0 Modern C++ Library
jsonrpc::transport::FramedSocketTransport Class Reference
Transport layer using Asio sockets for JSON-RPC communication with framing.
#include <framed_socket_transport.hpp>
Public Member Functions
FramedSocketTransport (const std::string &host, uint16_t port, bool isServer)
void SendMessage (const std::string &message) override
Sends a message in string to the transport layer.
std::string ReceiveMessage () override
Receives a message from the transport layer.
Public Member Functions inherited from jsonrpc::transport::SocketTransport
SocketTransport (const std::string &host, uint16_t port, bool isServer)
Constructs a SocketTransport.
~SocketTransport ()
void SendMessage (const std::string &message) override
Sends a message in string to the transport layer.
std::string ReceiveMessage () override
Receives a message from the transport layer.
Public Member Functions inherited from jsonrpc::transport::Transport
virtual ~Transport ()=default
Virtual destructor.
Additional Inherited Members
Protected Member Functions inherited from jsonrpc::transport::SocketTransport
asio::ip::tcp::socket & GetSocket ()
Protected Member Functions inherited from jsonrpc::transport::FramedTransport
void FrameMessage (std::ostream &output, const std::string &message)
Constructs a framed message.
HeaderMap ReadHeadersFromStream (std::istream &input)
int ReadContentLengthFromStream (std::istream &input)
std::string ReadContent (std::istream &input, int content_length)
Reads content from the input stream based on the content length.
std::string ReceiveFramedMessage (std::istream &input)
Receives a framed message.
Static Protected Attributes inherited from jsonrpc::transport::FramedTransport
static constexpr const char * HEADER_DELIMITER = "\r\n\r\n"
The delimiter used to separate headers from the message content.
Detailed Description
Transport layer using Asio sockets for JSON-RPC communication with framing.
Definition at line 17 of file framed_socket_transport.hpp.
Constructor & Destructor Documentation
FramedSocketTransport()
jsonrpc::transport::FramedSocketTransport::FramedSocketTransport (const std::string & host, uint16_t port, bool isServer)
Definition at line 12 of file framed_socket_transport.cpp.
    : SocketTransport(host, port, isServer), FramedTransport() {
  spdlog::info("FramedSocketTransport initialized with host: {} and port: {}",
      host, port);
}
Member Function Documentation
ReceiveMessage()
std::string jsonrpc::transport::FramedSocketTransport::ReceiveMessage () override virtual
Receives a message from the transport layer.
Returns
The JSON-RPC response as a string.
Implements jsonrpc::transport::Transport.
Definition at line 40 of file framed_socket_transport.cpp.
{
  asio::streambuf buffer;
  asio::error_code ec;
  // Read headers until \r\n\r\n delimiter
  asio::read_until(GetSocket(), buffer, HEADER_DELIMITER, ec);
  if (ec) {
    throw std::runtime_error("Failed to read message headers: " + ec.message());
  }
  std::istream headerStream(&buffer);
  // Extract content length from the headers
  int contentLength = ReadContentLengthFromStream(headerStream);
  // Calculate how much more content we need to read
  std::size_t remainingContentLength = contentLength - buffer.size();
  // Read any remaining content directly into the buffer
  if (remainingContentLength > 0) {
    asio::read(GetSocket(), buffer.prepare(remainingContentLength), ec);
    if (ec && ec != asio::error::eof) {
      throw std::runtime_error(
          "Failed to read message content: " + ec.message());
    }
    buffer.commit(remainingContentLength);
  }
  // Convert the entire buffer to a string
  std::string content(
      asio::buffers_begin(buffer.data()), asio::buffers_end(buffer.data()));
  return content;
}
References jsonrpc::transport::SocketTransport::GetSocket(), jsonrpc::transport::FramedTransport::HEADER_DELIMITER, and jsonrpc::transport::FramedTransport::ReadContentLengthFromStream().
SendMessage()
void jsonrpc::transport::FramedSocketTransport::SendMessage (const std::string & request) override virtual
Sends a message in string to the transport layer.
Parameters
request The JSON-RPC request as a string.
Implements jsonrpc::transport::Transport.
Definition at line 19 of file framed_socket_transport.cpp.
{
  try {
    asio::streambuf messageBuf;
    std::ostream messageStream(&messageBuf);
    FrameMessage(messageStream, message);
    asio::error_code ec;
    std::size_t bytesWritten = asio::write(GetSocket(), messageBuf.data(), ec);
    if (ec) {
      throw std::runtime_error("Error sending message: " + ec.message());
    }
    spdlog::info(
        "FramedSocketTransport sent message with {} bytes", bytesWritten);
  } catch (const std::exception &e) {
    spdlog::error("FramedSocketTransport failed to send message: {}", e.what());
    throw;
  }
}
References jsonrpc::transport::FramedTransport::FrameMessage(), and jsonrpc::transport::SocketTransport::GetSocket().
The documentation for this class was generated from the following files:
include/jsonrpc/transport/framed_socket_transport.hpp
src/transport/framed_socket_transport.cpp