JSON-RPC 2.0 Modern C++ Library
jsonrpc::server::transports::ServerTransport Class Reference abstract
Abstract base class for server transport mechanisms.
#include <server_transport.hpp>
Public Member Functions
ServerTransport ()
Constructs a ServerTransport object.
virtual ~ServerTransport ()=default
Virtual destructor for ServerTransport.
virtual void Start ()
Starts the transport.
virtual void Stop ()
Stops the transport.
void SetDispatcher (std::shared_ptr< IDispatcher > dispatcher)
Sets the dispatcher for the transport.
bool IsRunning () const
Checks if the transport is running.
Protected Member Functions
virtual void Listen ()=0
Listens for incoming messages.
Protected Attributes
std::atomic< bool > running_
Atomic flag indicating if the transport is running.
std::shared_ptr< IDispatcher > dispatcher_
Pointer to the Dispatcher object.
Detailed Description
Abstract base class for server transport mechanisms.
The ServerTransport class provides an interface for various transport mechanisms that a JSON-RPC server can use, such as stdio and HTTP. Concrete implementations must implement the Listen method to handle incoming messages.
Definition at line 19 of file server_transport.hpp.
Constructor & Destructor Documentation
ServerTransport()
jsonrpc::server::transports::ServerTransport::ServerTransport () inline
Constructs a ServerTransport object.
Definition at line 24 of file server_transport.hpp.
                    : dispatcher_(nullptr), running_(false) {
  }
~ServerTransport()
virtual jsonrpc::server::transports::ServerTransport::~ServerTransport () virtual default
Virtual destructor for ServerTransport.
Member Function Documentation
IsRunning()
bool jsonrpc::server::transports::ServerTransport::IsRunning () const inline
Checks if the transport is running.
Returns
True if the transport is running, false otherwise.
Definition at line 65 of file server_transport.hpp.
{
    return running_.load(std::memory_order_acquire);
  }
References running_.
Referenced by jsonrpc::server::transports::FramedStdioServerTransport::Listen(), and jsonrpc::server::transports::StdioServerTransport::Listen().
Listen()
virtual void jsonrpc::server::transports::ServerTransport::Listen () protected pure virtual
Listens for incoming messages.
This is a pure virtual method that must be implemented by concrete transport classes.
Implemented in jsonrpc::server::transports::FramedStdioServerTransport, and jsonrpc::server::transports::StdioServerTransport.
Referenced by Start().
SetDispatcher()
void jsonrpc::server::transports::ServerTransport::SetDispatcher (std::shared_ptr< IDispatcher > dispatcher) inline
Sets the dispatcher for the transport.
Parameters
dispatcher A shared pointer to the Dispatcher object.
Definition at line 56 of file server_transport.hpp.
{
    dispatcher_ = std::move(dispatcher);
  }
References dispatcher_.
Start()
virtual void jsonrpc::server::transports::ServerTransport::Start () inline virtual
Starts the transport.
This method sets the running state to true and calls the Listen method.
Definition at line 37 of file server_transport.hpp.
                       {
    running_.store(true, std::memory_order_release);
    Listen();
  }
References Listen(), and running_.
Stop()
virtual void jsonrpc::server::transports::ServerTransport::Stop () inline virtual
Stops the transport.
This method sets the running state to false.
Definition at line 47 of file server_transport.hpp.
                      {
    running_.store(false, std::memory_order_release);
  }
References running_.
Member Data Documentation
dispatcher_
std::shared_ptr<IDispatcher> jsonrpc::server::transports::ServerTransport::dispatcher_ protected
Pointer to the Dispatcher object.
Definition at line 82 of file server_transport.hpp.
Referenced by jsonrpc::server::transports::FramedStdioServerTransport::Listen(), jsonrpc::server::transports::StdioServerTransport::Listen(), and SetDispatcher().
running_
std::atomic<bool> jsonrpc::server::transports::ServerTransport::running_ protected
Atomic flag indicating if the transport is running.
Definition at line 79 of file server_transport.hpp.
Referenced by IsRunning(), Start(), and Stop().
The documentation for this class was generated from the following file:
include/jsonrpc/server/transports/server_transport.hpp