JSON-RPC 2.0 Modern C++ Library
jsonrpc::server::transports::FramedStdioServerTransport Class Reference
Server transport using framed stdio for communication.
#include <framed_stdio_server_transport.hpp>
Protected Member Functions
void Listen () override
Listens for incoming messages and dispatches them to the appropriate handlers.
Protected Member Functions inherited from jsonrpc::common::transports::FramedTransport
void FrameMessage (std::ostream &output, const std::string &message)
Constructs a framed message.
std::string DeframeMessage (std::istream &input)
Receives a framed message.
Additional Inherited Members
Public Member Functions inherited from jsonrpc::server::transports::ServerTransport
ServerTransport ()
Constructs a ServerTransport object.
virtual ~ServerTransport ()=default
Virtual destructor for ServerTransport.
virtual void Start ()
Starts the transport.
virtual void Stop ()
Stops the transport.
void SetDispatcher (std::shared_ptr< IDispatcher > dispatcher)
Sets the dispatcher for the transport.
bool IsRunning () const
Checks if the transport is running.
Protected Attributes inherited from jsonrpc::server::transports::ServerTransport
std::atomic< bool > running_
Atomic flag indicating if the transport is running.
std::shared_ptr< IDispatcher > dispatcher_
Pointer to the Dispatcher object.
Detailed Description
Server transport using framed stdio for communication.
This class implements the ServerTransport interface using framed stdio as the underlying transport mechanism.
Definition at line 18 of file framed_stdio_server_transport.hpp.
Member Function Documentation
Listen()
void jsonrpc::server::transports::FramedStdioServerTransport::Listen () override protected virtual
Listens for incoming messages and dispatches them to the appropriate handlers.
Implements jsonrpc::server::transports::ServerTransport.
Definition at line 14 of file framed_stdio_server_transport.cpp.
{
  spdlog::info("FramedStdioServerTransport listening");
  if (!dispatcher_) {
    spdlog::error("Dispatcher is not set.");
    return;
  }
  while (IsRunning()) {
    try {
      std::string content = DeframeMessage(std::cin);
      std::optional<std::string> response =
          dispatcher_->DispatchRequest(content);
      if (response.has_value()) {
        spdlog::debug("FramedStdioServerTransport dispatching response: {}",
            response.value());
        FrameMessage(std::cout, response.value());
        std::cout << std::flush;
      }
    } catch (const std::runtime_error &e) {
      spdlog::error(
          "Runtime error in FramedStdioServerTransport: {}", e.what());
      break; // Exit loop on error
    }
  }
}
References jsonrpc::common::transports::FramedTransport::DeframeMessage(), jsonrpc::server::transports::ServerTransport::dispatcher_, jsonrpc::common::transports::FramedTransport::FrameMessage(), and jsonrpc::server::transports::ServerTransport::IsRunning().
The documentation for this class was generated from the following files:
include/jsonrpc/server/transports/framed_stdio_server_transport.hpp
src/server/transports/framed_stdio_server_transport.cpp