JSON-RPC 2.0: json_rpc::Dispatcher Class Reference
json_rpc::Dispatcher Class Reference
A class responsible for dispatching JSON-RPC requests to the appropriate handlers.
#include <dispatcher.hpp>
Public Member Functions
Dispatcher (bool enableMultithreading=true, size_t numThreads=std::thread::hardware_concurrency())
Constructs a Dispatcher object.
virtual ~Dispatcher ()=default
Destructor for Dispatcher.
std::optional< std::string > DispatchRequest (const std::string &request)
Dispatches an RPC request to the appropriate handler.
void RegisterMethodCall (const std::string &method, const MethodCallHandler &handler)
Registers a method call handler for a specific method.
void RegisterNotification (const std::string &method, const NotificationHandler &handler)
Registers a notification handler for a specific method.
Detailed Description
A class responsible for dispatching JSON-RPC requests to the appropriate handlers.
The Dispatcher class enables the registration and execution of method call and notification handlers for JSON-RPC requests. Handlers can be registered using std::function, allowing for flexible and modern C++ usage. The Dispatcher can operate in single-threaded or multi-threaded mode, providing scalability for handling batch requests.
Definition at line 26 of file dispatcher.hpp.
Constructor & Destructor Documentation
Dispatcher()
json_rpc::Dispatcher::Dispatcher (bool enableMultithreading = true, size_t numThreads = std::thread::hardware_concurrency()) inline
Constructs a Dispatcher object.
Parameters
enableMultithreading Enable multi-threading support.
numThreads Number of threads to use if multi-threading is enabled.
Definition at line 34 of file dispatcher.hpp.
      : enableMultithreading_(enableMultithreading),
        thread_pool_(enableMultithreading ? numThreads : 0) {
  }
~Dispatcher()
virtual json_rpc::Dispatcher::~Dispatcher () virtual default
Destructor for Dispatcher.
Member Function Documentation
DispatchRequest()
std::optional< std::string > json_rpc::Dispatcher::DispatchRequest (const std::string & request)
Dispatches an RPC request to the appropriate handler.
Parameters
request The JSON-RPC request as a string.
Returns
The response from the handler as a JSON string, or std::nullopt if no response is needed.
Definition at line 7 of file dispatcher.cpp.
{
  auto requestJson = ParseAndValidateJson(requestStr);
  if (!requestJson.has_value()) {
    return Response::CreateLibError(LibErrorKind::ParseError).ToStr();
  }
  if (requestJson->is_array()) {
    return DispatchBatchRequest(*requestJson);
  } else {
    return DispatchSingleRequest(*requestJson);
  }
}
References json_rpc::Response::CreateLibError(), json_rpc::ParseError, and json_rpc::Response::ToStr().
Referenced by json_rpc::HttpServerTransport::HttpServerTransport(), json_rpc::FramedStdioServerTransport::Listen(), and json_rpc::StdioServerTransport::Listen().
RegisterMethodCall()
void json_rpc::Dispatcher::RegisterMethodCall (const std::string & method, const MethodCallHandler & handler)
Registers a method call handler for a specific method.
Parameters
method The name of the method.
handler The handler function to be called for this method.
Definition at line 199 of file dispatcher.cpp.
{
  handlers_[method] = handler;
  spdlog::info("Dispatcher registered method call: {}", method);
}
RegisterNotification()
void json_rpc::Dispatcher::RegisterNotification (const std::string & method, const NotificationHandler & handler)
Registers a notification handler for a specific method.
Parameters
method The name of the method.
handler The handler function to be called for this notification.
Definition at line 205 of file dispatcher.cpp.
{
  handlers_[method] = handler;
  spdlog::info("Dispatcher registered notification: {}", method);
}
The documentation for this class was generated from the following files:
include/json_rpc/core/dispatcher.hpp
src/core/dispatcher.cpp