JSON-RPC 2.0: json_rpc::Request Class Reference
json_rpc::Request Class Reference
Represents a JSON-RPC request.
#include <request.hpp>
Public Member Functions
Request (const std::string &method, const std::optional< Json > &params=std::nullopt, std::optional< Json > id=std::nullopt)
Constructs a Request object.
Json ToJson () const
Serializes the Request object to a JSON object.
std::string GetMethod () const
Gets the method name.
std::optional< Json > GetParams () const
Gets the parameters.
std::optional< Json > GetId () const
Gets the request ID.
Static Public Member Functions
static Request FromJson (const Json &jsonObj)
Creates a Request object from a JSON object.
Detailed Description
Represents a JSON-RPC request.
Definition at line 13 of file request.hpp.
Constructor & Destructor Documentation
Request()
json_rpc::Request::Request (const std::string & method, const std::optional< Json > & params = std::nullopt, std::optional< Json > id = std::nullopt) inline explicit
Constructs a Request object.
Parameters
method The name of the method to be invoked.
params The parameters for the method (optional).
id The ID of the request (optional).
Definition at line 22 of file request.hpp.
      : method_(method), params_(params), id_(id) {
  }
Referenced by FromJson().
Member Function Documentation
FromJson()
Request json_rpc::Request::FromJson (const Json & jsonObj) static
Creates a Request object from a JSON object.
Parameters
jsonObj The JSON object representing the request.
Returns
A Request object.
Definition at line 5 of file request.cpp.
{
  auto params = jsonObj.contains("params")
                    ? std::optional<Json>(jsonObj["params"])
                    : std::nullopt;
  auto id = jsonObj.contains("id") ? std::optional<Json>(jsonObj["id"])
                                   : std::nullopt;
  return Request(jsonObj["method"], params, id);
}
References Request().
GetId()
std::optional< Json > json_rpc::Request::GetId () const inline
Gets the request ID.
Definition at line 54 of file request.hpp.
{
    return id_;
  }
GetMethod()
std::string json_rpc::Request::GetMethod () const inline
Gets the method name.
Definition at line 44 of file request.hpp.
{
    return method_;
  }
GetParams()
std::optional< Json > json_rpc::Request::GetParams () const inline
Gets the parameters.
Definition at line 49 of file request.hpp.
{
    return params_;
  }
ToJson()
Json json_rpc::Request::ToJson () const
Serializes the Request object to a JSON object.
Returns
The JSON representation of the request.
Definition at line 14 of file request.cpp.
{
  Json jsonObj;
  jsonObj["jsonrpc"] = "2.0";
  jsonObj["method"] = method_;
  if (params_.has_value()) {
    jsonObj["params"] = params_.value();
  }
  if (id_.has_value()) {
    jsonObj["id"] = id_.value();
  }
  return jsonObj;
}
Referenced by json_rpc::Client::SendMethodCall(), and json_rpc::Client::SendNotification().
The documentation for this class was generated from the following files:
include/json_rpc/core/request.hpp
src/core/request.cpp