JSON-RPC 2.0 Modern C++ Library
jsonrpc::transport::FramedTransport Class Reference
Base class for framed transport mechanisms.
#include <framed_transport.hpp>
Protected Member Functions
void FrameMessage (std::ostream &output, const std::string &message)
Constructs a framed message.
HeaderMap ReadHeadersFromStream (std::istream &input)
int ReadContentLengthFromStream (std::istream &input)
std::string ReadContent (std::istream &input, int content_length)
Reads content from the input stream based on the content length.
std::string ReceiveFramedMessage (std::istream &input)
Receives a framed message.
Static Protected Attributes
static constexpr const char * HEADER_DELIMITER = "\r\n\r\n"
The delimiter used to separate headers from the message content.
Friends
class FramedTransportTest
Detailed Description
Base class for framed transport mechanisms.
Provides modular functionality for sending and receiving framed messages.
Definition at line 18 of file framed_transport.hpp.
Member Function Documentation
FrameMessage()
void jsonrpc::transport::FramedTransport::FrameMessage (std::ostream & output, const std::string & message) protected
Constructs a framed message.
Constructs a JSON message as a string with additional headers for Content-Length and Content-Type, similar to HTTP.
Parameters
output The output stream to write the framed message.
message The message to be framed.
Definition at line 11 of file framed_transport.cpp.
{
  output << "Content-Length: " << message.size() << "\r\n"
         << "Content-Type: application/vscode-jsonrpc; charset=utf-8\r\n"
         << "\r\n"
         << message;
}
Referenced by jsonrpc::transport::FramedPipeTransport::SendMessage(), and jsonrpc::transport::FramedStdioTransport::SendMessage().
ReadContent()
std::string jsonrpc::transport::FramedTransport::ReadContent (std::istream & input, int content_length) protected
Reads content from the input stream based on the content length.
Parameters
input The input stream to read the content from.
content_length The length of the content to be read.
Returns
The content as a string.
Definition at line 49 of file framed_transport.cpp.
{
  std::string content(content_length, '\0');
  input.read(&content[0], content_length);
  if (input.gcount() != content_length) {
    throw std::runtime_error("Failed to read the expected content length");
  }
  return content;
}
Referenced by ReceiveFramedMessage().
ReadContentLengthFromStream()
int jsonrpc::transport::FramedTransport::ReadContentLengthFromStream (std::istream & input) protected
Definition at line 40 of file framed_transport.cpp.
{
  auto headers = ReadHeadersFromStream(input);
  auto it = headers.find("Content-Length");
  if (it == headers.end()) {
    throw std::runtime_error("Content-Length header missing");
  }
  return ParseContentLength(it->second);
}
References ReadHeadersFromStream().
Referenced by ReceiveFramedMessage(), and jsonrpc::transport::FramedPipeTransport::ReceiveMessage().
ReadHeadersFromStream()
FramedTransport::HeaderMap jsonrpc::transport::FramedTransport::ReadHeadersFromStream (std::istream & input) protected
Definition at line 19 of file framed_transport.cpp.
                       {
  HeaderMap headers;
  std::string line;
  while (std::getline(input, line) && !line.empty() && line != "\r") {
    auto colonPos = line.find(':');
    if (colonPos != std::string::npos) {
      std::string header_key = utils::trim(line.substr(0, colonPos));
      std::string header_value = utils::trim(line.substr(colonPos + 1));
      headers[header_key] = header_value;
    }
  }
  if (headers.empty()) {
    throw std::runtime_error("Failed to read headers");
  }
  return headers;
}
References jsonrpc::utils::trim().
Referenced by ReadContentLengthFromStream().
ReceiveFramedMessage()
std::string jsonrpc::transport::FramedTransport::ReceiveFramedMessage (std::istream & input) protected
Receives a framed message.
Reads headers to determine the content length, then reads the message content based on that length.
Parameters
input The input stream to read the framed message.
Returns
The received message content.
Definition at line 59 of file framed_transport.cpp.
{
  int content_length = ReadContentLengthFromStream(input);
  return ReadContent(input, content_length);
}
References ReadContent(), and ReadContentLengthFromStream().
Referenced by jsonrpc::transport::FramedStdioTransport::ReceiveMessage().
Friends And Related Symbol Documentation
FramedTransportTest
friend class FramedTransportTest friend
Definition at line 69 of file framed_transport.hpp.
Member Data Documentation
HEADER_DELIMITER
const char* jsonrpc::transport::FramedTransport::HEADER_DELIMITER = "\r\n\r\n" static constexpr protected
The delimiter used to separate headers from the message content.
Definition at line 24 of file framed_transport.hpp.
Referenced by jsonrpc::transport::FramedPipeTransport::ReceiveMessage().
The documentation for this class was generated from the following files:
include/jsonrpc/transport/framed_transport.hpp
src/transport/framed_transport.cpp