JSON-RPC 2.0: json_rpc::ServerTransport Class Reference
json_rpc::ServerTransport Class Reference abstract
Abstract base class for server transport mechanisms.
#include <server_transport.hpp>
Public Member Functions
ServerTransport ()
Constructs a ServerTransport object.
virtual ~ServerTransport ()=default
Virtual destructor for ServerTransport.
virtual void Start ()
Starts the transport.
virtual void Stop ()
Stops the transport.
void SetDispatcher (Dispatcher *dispatcher)
Sets the dispatcher for the transport.
bool IsRunning () const
Checks if the transport is running.
Protected Member Functions
virtual void Listen ()=0
Listens for incoming messages.
Protected Attributes
std::atomic< bool > running_
Atomic flag indicating if the transport is running.
Dispatcher * dispatcher_
Pointer to the Dispatcher object.
Detailed Description
Abstract base class for server transport mechanisms.
The ServerTransport class provides an interface for various transport mechanisms that a JSON-RPC server can use, such as stdio and HTTP. Concrete implementations must implement the Listen method to handle incoming messages.
Definition at line 18 of file server_transport.hpp.
Constructor & Destructor Documentation
ServerTransport()
json_rpc::ServerTransport::ServerTransport () inline
Constructs a ServerTransport object.
Definition at line 23 of file server_transport.hpp.
                    : dispatcher_(nullptr), running_(false) {
  }
~ServerTransport()
virtual json_rpc::ServerTransport::~ServerTransport () virtual default
Virtual destructor for ServerTransport.
Member Function Documentation
IsRunning()
bool json_rpc::ServerTransport::IsRunning () const inline
Checks if the transport is running.
Returns
True if the transport is running, false otherwise.
Definition at line 64 of file server_transport.hpp.
{
    return running_.load(std::memory_order_acquire);
  }
References running_.
Referenced by json_rpc::FramedStdioServerTransport::Listen(), and json_rpc::StdioServerTransport::Listen().
Listen()
virtual void json_rpc::ServerTransport::Listen () protected pure virtual
Listens for incoming messages.
This is a pure virtual method that must be implemented by concrete transport classes.
Implemented in json_rpc::FramedStdioServerTransport, json_rpc::HttpServerTransport, and json_rpc::StdioServerTransport.
Referenced by Start().
SetDispatcher()
void json_rpc::ServerTransport::SetDispatcher (Dispatcher * dispatcher) inline
Sets the dispatcher for the transport.
Parameters
dispatcher A pointer to the Dispatcher object.
Definition at line 55 of file server_transport.hpp.
{
    dispatcher_ = dispatcher;
  }
References dispatcher_.
Start()
virtual void json_rpc::ServerTransport::Start () inline virtual
Starts the transport.
This method sets the running state to true and calls the Listen method.
Definition at line 36 of file server_transport.hpp.
                       {
    running_.store(true, std::memory_order_release);
    Listen();
  }
References Listen(), and running_.
Stop()
virtual void json_rpc::ServerTransport::Stop () inline virtual
Stops the transport.
This method sets the running state to false.
Reimplemented in json_rpc::HttpServerTransport.
Definition at line 46 of file server_transport.hpp.
                      {
    running_.store(false, std::memory_order_release);
  }
References running_.
Member Data Documentation
dispatcher_
Dispatcher* json_rpc::ServerTransport::dispatcher_ protected
Pointer to the Dispatcher object.
Definition at line 81 of file server_transport.hpp.
Referenced by json_rpc::HttpServerTransport::HttpServerTransport(), json_rpc::FramedStdioServerTransport::Listen(), json_rpc::StdioServerTransport::Listen(), and SetDispatcher().
running_
std::atomic<bool> json_rpc::ServerTransport::running_ protected
Atomic flag indicating if the transport is running.
Definition at line 78 of file server_transport.hpp.
Referenced by IsRunning(), Start(), and Stop().
The documentation for this class was generated from the following file:
include/json_rpc/core/server_transport.hpp