name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Conan
        uses: hankhsu1996/setup-conan@v1
        with:
          conan-version: "2.5.0"
          cache-dependencies: true
          cache-tool: true

      - name: Install dependencies
        run: |
          conan profile detect --force
          conan install . --build=missing

      - name: Configure CMake and build project
        run: |
          cmake --preset release
          cmake --build --preset release

      - name: Upload necessary build files
        uses: actions/upload-artifact@v4
        with:
          name: build-files
          path: |
            build/Release/CMakeCache.txt
            build/Release/CTestTestfile.cmake
            build/Release/tests/tests
          retention-days: 7

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download necessary build files
        uses: actions/download-artifact@v4
        with:
          name: build-files
          path: build

      - name: Add execute permissions to test binary
        run: chmod +x build/Release/tests/tests

      - name: Run tests
        run: ctest --preset release --test-dir build/Release

  docs:
    runs-on: ubuntu-latest
    container: hankhsu1996/doxygen:1.11.0

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Generate Doxygen documentation
        run: doxygen docs/Doxyfile

      - name: Upload Doxygen documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: doxygen-docs
          path: docs/generated/html

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: docs
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download Doxygen documentation artifacts
        uses: actions/download-artifact@v4
        with:
          name: doxygen-docs
          path: docs/generated/html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/generated/html
          publish_branch: gh-pages
