name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.4"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ninja-build
          python -m pip install --upgrade pip
          pip install conan

      - name: Detect Conan profile
        run: conan profile detect --force

      - name: Install Conan dependencies
        run: conan install . --output-folder=build --build=missing

      - name: Configure
        run: cmake --preset default

      - name: Build
        run: cmake --build --preset default

      - name: Test
        run: ctest --preset default
