name: Generate and Deploy Doxygen Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: |
          DOXYGEN_VERSION=1.10.0
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_10_0/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          tar -xzf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          sudo cp -r doxygen-${DOXYGEN_VERSION}/bin/* /usr/local/bin/

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Upload Doxygen documentation artifacts
        if: github.event_name == 'pull_request'
        uses: actions/upload-artifact@v2
        with:
          name: doxygen-docs
          path: docs/html

  deploy:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Doxygen
        run: |
          DOXYGEN_VERSION=1.10.0
          wget https://github.com/doxygen/doxygen/releases/download/Release_1_10_0/doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          tar -xzf doxygen-${DOXYGEN_VERSION}.linux.bin.tar.gz
          sudo cp -r doxygen-${DOXYGEN_VERSION}/bin/* /usr/local/bin/

      - name: Generate Doxygen documentation
        run: doxygen Doxyfile

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          publish_branch: gh-pages
